dataFile <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
dataFile1 <- transform(dataFile, Date = as.character(Date))
y <- subset(dataFile1, Date == "1/2/2007")
z <- rbind(y, subset(dataFile1, Date == "2/2/2007"))
a <- transform(z, Global_active_power = as.numeric(as.character(Global_active_power)))
b <- transform(a, Time = as.character(Time))
b$New <- paste(b[["Date"]], b[["Time"]])
d <- transform(b, New = strptime(b[, "New"], "%d/%m/%Y %H:%M:%S"))
f <- transform(d, Sub_metering_1 = as.numeric(as.character(Sub_metering_1)))
g <- transform(f, Sub_metering_2 = as.numeric(as.character(Sub_metering_2)))
h <- transform(g, Sub_metering_3 = as.numeric(as.character(Sub_metering_3)))
png(file = "plot3.png")
plot(d[, "New"], d[, "Sub_metering_1"], yaxt = "n", type = "l", xlab = "", ylab = "Energy sub metering")
axis(2, c(0, 10, 20, 30))
lines(d[, "New"], d[, "Sub_metering_2"], col = "red")
lines(d[, "New"], d[, "Sub_metering_3"], col = "blue")
legend("topright", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
dev.off()