dataFile <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
dataFile1 <- transform(dataFile, Date = as.character(Date))
y <- subset(dataFile1, Date == "1/2/2007")
z <- rbind(y, subset(dataFile1, Date == "2/2/2007"))
a <- transform(z, Global_active_power = as.numeric(as.character(Global_active_power)))
b <- transform(a, Time = as.character(Time))
b$New <- paste(b[["Date"]], b[["Time"]])
d <- transform(b, New = strptime(b[, "New"], "%d/%m/%Y %H:%M:%S"))
png(file = "plot2.png")
plot(d[, "New"], d[, "Global_active_power"], type = "l", xlab = "", ylab = "Global Active Power (kilowatts)")
dev.off()