dataFile <- read.table("household_power_consumption.txt", header = TRUE, sep = ";")
dataFile1 <- transform(dataFile, Date = as.character(Date))
y <- subset(dataFile1, Date == "1/2/2007")
z <- rbind(y, subset(dataFile1, Date == "2/2/2007"))
a <- transform(z, Global_active_power = as.numeric(as.character(Global_active_power)))
b <- transform(a, Time = as.character(Time))
b$New <- paste(b[["Date"]], b[["Time"]])
d <- transform(b, New = strptime(b[, "New"], "%d/%m/%Y %H:%M:%S"))
f <- transform(d, Sub_metering_1 = as.numeric(as.character(Sub_metering_1)))
g <- transform(f, Sub_metering_2 = as.numeric(as.character(Sub_metering_2)))
h <- transform(g, Sub_metering_3 = as.numeric(as.character(Sub_metering_3)))
i <- transform(h, Voltage = as.numeric(as.character(Voltage)))
j <- transform(i, Global_reactive_power = as.numeric(as.character(Global_reactive_power)))
png(file = "plot4.png")
par(mfrow = c(2,2))
plot(j[, "New"], j[, "Global_active_power"], type = "l", xlab = "", ylab = "Global Active Power")
plot(j[, "New"], j[, "Voltage"], type = "l", xlab = "datetime", ylab = "Voltage")
plot(j[, "New"], j[, "Sub_metering_1"], type = "l", xlab = "", ylab = "Energy sub metering")
lines(j[, "New"], j[, "Sub_metering_2"], col = "red")
lines(j[, "New"], j[, "Sub_metering_3"], col = "blue")
legend("topright", lwd = 1, col = c("black", "red", "blue"), legend = c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
plot(j[, "New"], j[, "Global_reactive_power"], type = "l", xlab = "datetime", ylab = "Global_reactive_power")
dev.off()